version: "2.1"

services:
  digitaltwinbrokerservice:
    image: ${REPOSITORY}/onesaitplatform/digitaltwin:${MODULE_TAG}
    container_name: digitaltwinbrokerservice   
    environment:
      - REALTIMEDBUSEAUTH=false          
    networks:
      - op-data_datanetwork
    ports:
     - "19300:19300"
    external_links:
     - configdb
networks:
  op-data_datanetwork:
    external: true
