version: "2.1"

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    networks:
      - op-data_datanetwork    
    ports:
      - "90:90"
    volumes:  
      - ${NGINX_VOLUME}:/etc/nginx/nginx.conf:rw
    restart: on-failure
networks:
  op-data_datanetwork:
    external: true