version: "2.1"

services:
  cacheservice:
    container_name: cacheserver
    environment:
      - REALTIMEDBUSEAUTH=false    
    networks:
      - op-data_datanetwork
    image: ${REPOSITORY}/onesaitplatform/cacheservice:${MODULE_TAG}
    external_links:
      - controlpanelservice
  routerservice:
    container_name: router
    networks:
      - op-data_datanetwork
    image: ${REPOSITORY}/onesaitplatform/router:${MODULE_TAG}
    environment:
      - SERVER_NAME="localhost"
      - REALTIMEDBUSEAUTH=false
networks:
  op-data_datanetwork:
    external: true
