version: "2.1"

services:         
  controlpanelservice:
    image: ${REPOSITORY}/onesaitplatform/controlpanel:${MODULE_TAG}
    container_name: controlpanelservice 
    environment:
      - REALTIMEDBUSEAUTH=false 
      - ONESAIT_PROPERTIES={"onesaitplatform":{"secure.cookie":false}}
    networks:
      - op_data_datanetwork
    ports:
     - "18000:18000"
    external_links:
     - configdb
     - schedulerdb
     - realtimedb 
networks:
  op_data_datanetwork:
    external: true
